                    #\\\\\\\\\\\\\\\/////////////////#
                    ###        Workspaces          ###
                    #\\\\\\\\\\\\\\\/////////////////#

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\//////////////////////////////////////////////////#

# NOOB-NOTE: Workspaces in Hyprland
# Workspaces help you organize your windows into separate "virtual desktops". Each workspace can be assigned
# to a different monitor, giving you a multi-monitor setup where you can switch between workspaces easily.

#NOTICE: This configuration is intended specifically for workspace monitor assignment in the event
# that you have multiple monitors. If you are single monitor, I belive you can set to "auto" for all.
# Custom workspace appearances are managed in the $HOME/.config/hypr/config/aesthetics.conf file.

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\//////////////////////////////////////////////////#

source = $HOME/.config/hypr/configs/variables.conf

#If you only have 1 monitor i.e. laptop, just comment these out or delete them.
#MONITOR 1
workspace = 1, name:CODE, monitor:$mainDisplay
workspace = 2, name:WORK, monitor:$mainDisplay
workspace = 3, name:EXTRA-1, monitor:$mainDisplay

#MONITOR 2
workspace = 4, name:SEARCH, monitor:$secondaryDisplay
workspace = 5, name:EXTRA-2, monitor:$secondaryDisplay

#SPECIAL WORKSPACES
workspace = SPECIAL, name:SCRATCH,
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\//////////////////////////////////////////////////#
